FROM node:21 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
COPY .env.docker .env.local
RUN npm run build

#serve with nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD [ "nginx", "g", "deamon off;"]
