kind: Deployment
apiVersion: apps/v1
metadata: 
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          env:
            - name: MONGODB_URI
              value: {{ .Values.backend.env.MONGODB_URI }}
          ports:
            - containerPort: {{ .Values.backend.port }}