apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
  type: NodePort
  selector: 
    app: app-frontend