kind: Deployment
apiVersion: apps/v1
metadata: 
  name: backend
  annotations: 
    kubernetes.io/change-cause: "backend updated to e6dd45e"
  labels:
    app: app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: anandu408/blogapp_backend:e6dd45e
          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service:27017/wanderlust
          ports:
            - containerPort: 5000