apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations: 
    kubernetes.io/change-cause: "frontend updated to 04b568e"
  labels:
    app: app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: anandu408/blogapp_frontend:04b568e
          imagePullPolicy: Always
          ports:
            - containerPort: 80