apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage-mongo-0
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClass: manual
  hostPath:
    path: /data/db
    