backend:
  image: anandu408/mernapp-backend
  replicas: 2
  port: 5000
  env:
    MONGODB_URI: "mongodb://mongo-service:27017/wanderlust"

frontend:
  image: anandu408/mernapp-frontend
  replicas: 2
  port: 5173
  env:
    VITE_API_PATH: "http://backend:5000"
mongo:
  image: mongo:4.4
  replicas: 1
  port: 27017